#!/bin/python

import math
import os
import random
import re
import sys

n=int(input(""))
n=n%2

if (n==1 or (n==0 and 6<=n<=20)):
    print("Weird")
elif(n==0 and (2<=n<=5 or n>20)):
    print("Not Weird")
else:
    print("Not Weird")
