#!/bin/python
import math
import os
import random
import re
import sys

a=int(input(""))
n=a%2

if (n==1 or (n==0 and 6<=a<=20)):
    print("Weird")
elif(n==0 and (2<=a<=5 or a>20)):
    print("Not Weird")
else:
    print("Not Weird")
